yarnPath: .yarn/releases/yarn-4.4.1.cjs
nodeLinker: pnp
enableGlobalCache: false
supportedArchitectures:
  os:
    - "current"
    - "darwin"
    - "linux"
    - "win32"

  cpu:
    - "current"
    - "x86"
    - "x64"
    - "arm64"
    - "ia32"
